// Reads `brand/design.json` and emits two build-time artefacts the template
// consumes:
//   - `app/theme.generated.css` — :root CSS variables consumed by the
//     `@theme` block in `app/globals.css` (Tailwind v4 reads these).
//   - `lib/themeFonts.generated.ts` — exports the Google Fonts <link> href
//     so `app/layout.tsx` injects exactly the picked display+body families.
//
// If `brand/design.json` is missing or malformed we fall back to the
// DEFAULTS below so the template always builds, even on a fresh template
// clone before the design pass has run.
//
// Pure runtime: zero deps beyond `node:fs/promises` + `node:path` + `node:url`.

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(dirname(fileURLToPath(import.meta.url))); // .../lila-site-template
const DESIGN_PATH = join(ROOT, 'brand', 'design.json');
const CSS_OUT     = join(ROOT, 'app', 'theme.generated.css');
const FONTS_OUT   = join(ROOT, 'lib', 'themeFonts.generated.ts');

const DEFAULTS = {
  palette: {
    primary:    { hex: '#7c5cff', onHex: '#ffffff' },
    secondary:  { hex: '#1f1b3a', onHex: '#ffffff' },
    accent:     { hex: '#ff7a59', onHex: '#14121c' },
    surface:    { hex: '#ffffff', onHex: '#14121c' },
    surfaceAlt: { hex: '#f6f4fb', onHex: '#14121c' },
    text:       { hex: '#14121c' },
    muted:      { hex: '#5b5870' },
    border:     { hex: '#ece9f5' },
  },
  typography: {
    display: {
      family: 'Inter',
      weights: [500, 700],
      googleFontHref: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap',
    },
    body:   { family: 'Inter', weights: [400, 600] },
    scale:  'standard',
    radius: 'rounded',
  },
};

const RADIUS_PX = { sharp: '0', rounded: '14px', pill: '999px' };

async function loadDesign() {
  if (!existsSync(DESIGN_PATH)) return DEFAULTS;
  try {
    const raw = JSON.parse(await readFile(DESIGN_PATH, 'utf8'));
    return {
      palette: { ...DEFAULTS.palette, ...(raw.palette ?? {}) },
      typography: { ...DEFAULTS.typography, ...(raw.typography ?? {}) },
    };
  } catch {
    return DEFAULTS;
  }
}

function buildCss(design) {
  const p = design.palette;
  const t = design.typography;
  const radius = RADIUS_PX[t.radius] ?? RADIUS_PX.rounded;
  const display = JSON.stringify(t.display.family);
  const body    = JSON.stringify(t.body.family);
  return `/* GENERATED by scripts/applyDesign.mjs — do not edit by hand.
 * Source: brand/design.json (falls back to template defaults when missing). */
:root {
  --brand-primary: ${p.primary.hex};
  --brand-on-primary: ${p.primary.onHex};
  --brand-secondary: ${p.secondary.hex};
  --brand-on-secondary: ${p.secondary.onHex};
  --brand-accent: ${p.accent.hex};
  --brand-on-accent: ${p.accent.onHex};
  --brand-surface: ${p.surface.hex};
  --brand-on-surface: ${p.surface.onHex};
  --brand-surface-alt: ${p.surfaceAlt.hex};
  --brand-on-surface-alt: ${p.surfaceAlt.onHex};
  --brand-text: ${p.text.hex};
  --brand-muted: ${p.muted.hex};
  --brand-border: ${p.border.hex};
  --brand-font-display: ${display}, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
  --brand-font-body: ${body}, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
  --brand-radius-card: ${radius};
}
`;
}

function buildFontsModule(design) {
  const href = design.typography?.display?.googleFontHref ?? '';
  return `// GENERATED by scripts/applyDesign.mjs — do not edit by hand.
// Used by app/layout.tsx to inject the picked Google Fonts <link>.
export const googleFontsHref = ${JSON.stringify(href)};
`;
}

async function main() {
  const design = await loadDesign();
  await mkdir(dirname(CSS_OUT),   { recursive: true });
  await mkdir(dirname(FONTS_OUT), { recursive: true });
  await writeFile(CSS_OUT,   buildCss(design),         'utf8');
  await writeFile(FONTS_OUT, buildFontsModule(design), 'utf8');
  // eslint-disable-next-line no-console
  console.log(`[applyDesign] wrote ${CSS_OUT.replace(ROOT, '.')}`);
  console.log(`[applyDesign] wrote ${FONTS_OUT.replace(ROOT, '.')}`);
}

main().catch((err) => {
  console.error('[applyDesign] failed:', err);
  process.exit(1);
});
